
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usrlab06
 */
public class FormMenu extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        model = ((DefaultTableModel) tableStatus.getModel());
        model.setNumRows(0);
        popularVagas();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        lblData.setText(sdf.format(new Date()));

        Arquivo file = new Arquivo();

        for (int i = 0; i < file.consultar().length; i++) {
            String[] text = file.consultar();
            if (!text[0].equals("")) {
                String[] veiculo = file.consultar();
                String[] split = veiculo[i].split(";");

                model.addRow(split);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCPlaca = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblVaga = new javax.swing.JLabel();
        tfCPlaca = new javax.swing.JTextField();
        tfTipo = new javax.swing.JTextField();
        buttonCadastrar = new javax.swing.JButton();
        lblCadastro = new javax.swing.JLabel();
        cbVaga = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblRPlaca = new javax.swing.JLabel();
        tfRPlaca = new javax.swing.JTextField();
        buttonRetirar = new javax.swing.JButton();
        lblRetirar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStatus = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        buttonLimpar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de vagas");
        setMaximumSize(new java.awt.Dimension(730, 650));
        setPreferredSize(new java.awt.Dimension(730, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel1.setName(""); // NOI18N

        lblCPlaca.setText("Placa do veiculo:");

        lblTipo.setText("Tipo do veiculo:");

        lblVaga.setText("Vaga:");

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        lblCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCadastro.setText("Cadastrar Veiculo");

        cbVaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar>" }));
        cbVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCadastro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipo)
                                    .addComponent(lblCPlaca))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVaga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(buttonCadastrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPlaca)
                    .addComponent(tfCPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaga)
                    .addComponent(cbVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel2.setName(""); // NOI18N

        lblRPlaca.setText("Placa do veiculo:");

        buttonRetirar.setText("Retirar");
        buttonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRetirarActionPerformed(evt);
            }
        });

        lblRetirar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRetirar.setText("Retirar Veiculo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRetirar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonRetirar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblRPlaca)
                                .addGap(13, 13, 13)
                                .addComponent(tfRPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRetirar)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRPlaca)
                    .addComponent(tfRPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRetirar)
                .addGap(32, 32, 32))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(0));

        tableStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Tipo do veiculo", "Hora de entrada", "Hora de saida", "Vaga"
            }
        ));
        tableStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tableStatus);

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatus.setText("Status do Estacionamento");

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(lblStatus)
                        .addGap(82, 82, 82)
                        .addComponent(buttonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(buttonRemover))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(buttonLimpar)
                    .addComponent(buttonRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        lblData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData.setText("00/00/00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblData)
                .addGap(313, 313, 313))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblData)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        if (tfCPlaca.getText().isEmpty() || tfTipo.getText().isEmpty() || cbVaga.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Preencha os campos !");
        } else {
            int count = model.getRowCount();
            boolean vagaOcupada = false;
            boolean veiculoCadastrado = false;
            String info = "";
            for (int i = 0; i < count; i++) {
                String m = model.getValueAt(i, 4) + "";

                if (m.equals(cbVaga.getSelectedItem())) {
                    info += "Vaga Ocupada !";
                    vagaOcupada = true;
                }

            }
            for (int i = 0; i < count; i++) {
                String m = model.getValueAt(i, 0) + "";

                if (m.equals(tfCPlaca.getText())) {
                    if (vagaOcupada) {
                        info += "\n";
                    }
                    info += "Veiculo ja cadastrado !";
                    veiculoCadastrado = true;
                }
            }

            if (vagaOcupada || veiculoCadastrado) {
                JOptionPane.showMessageDialog(this, info);
            }

            if (!vagaOcupada && !veiculoCadastrado) {

                Veiculo v = new Veiculo();

                v.setPlaca(tfCPlaca.getText());
                v.setTipo(tfTipo.getText());

                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm");

                v.setHoraEntrada(sdf.format(new Date()));
                v.setHoraSaida("-");
                v.setVaga(cbVaga.getSelectedItem().toString());

                Arquivo file = new Arquivo();
                file.cadastrar(v);

                model.addRow(new String[]{v.getPlaca(), v.getTipo(), v.getHoraEntrada(), "-", v.getVaga()});

                tfCPlaca.setText("");
                tfTipo.setText("");
                cbVaga.setSelectedIndex(0);

            }

        }

        limparCampos();
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void buttonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRetirarActionPerformed
        int count = model.getRowCount();
        boolean temPlaca = false;

        if (tfRPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha os campos !");
        } else {
            if (count > 0) {
                for (int i = 0; i < count; i++) {
                    String mPlaca = model.getValueAt(i, 0) + "";
                    String mSaida = model.getValueAt(i, 3) + "";

                    if (mPlaca.equals(tfRPlaca.getText())) {
                        if (mSaida.equals("-")) {
                            Veiculo v = new Veiculo();

                            v.setPlaca(model.getValueAt(i, 0) + "");
                            v.setTipo(model.getValueAt(i, 1) + "");
                            v.setHoraEntrada(model.getValueAt(i, 2) + "");

                            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm");

                            v.setHoraSaida(sdf.format(new Date()));
                            v.setVaga("-");

                            model.removeRow(i);
                            model.addRow(new String[]{v.getPlaca(), v.getTipo(), v.getHoraEntrada(), v.getHoraSaida(), v.getVaga()});

                            attArq();

                            tfRPlaca.setText("");
                        } else {
                            JOptionPane.showMessageDialog(this, "Veiculo ja retirado !");
                        }
                        temPlaca = true;
                    }

                }
                if (!temPlaca) {
                    JOptionPane.showMessageDialog(this, "Placa não encontrada !");
                }
            } else {
                JOptionPane.showMessageDialog(this, "O estacionamento esta vazio !");
            }

        }
        limparCampos();
    }//GEN-LAST:event_buttonRetirarActionPerformed

    private void cbVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVagaActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        while (model.getRowCount() > 0) {
            model.removeRow(model.getRowCount() - 1);
        }
        Arquivo file = new Arquivo();
        file.limpar();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed


    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        attArq();
    }//GEN-LAST:event_formWindowClosing

    private void attArq() {
        Arquivo file = new Arquivo();
        file.limpar();
        int count = model.getRowCount();
        for (int i = 0; i < count; i++) {
            Veiculo v = new Veiculo();

            v.setPlaca(model.getValueAt(i, 0) + "");
            v.setTipo(model.getValueAt(i, 1) + "");
            v.setHoraEntrada(model.getValueAt(i, 2) + "");
            v.setHoraSaida(model.getValueAt(i, 3) + "");
            v.setVaga(model.getValueAt(i, 4) + "");

            file.cadastrar(v);
        }
    }

    private void limparCampos() {
        tfCPlaca.setText("");
        tfTipo.setText("");
        cbVaga.setSelectedIndex(0);
        tfRPlaca.setText("");
    }

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        model.removeRow(tableStatus.getSelectedRow());

        attArq();
    }//GEN-LAST:event_buttonRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    private void popularVagas() {
        for (int i = 1; i <= 20; i++) {
            cbVaga.addItem(i + "");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JButton buttonRetirar;
    private javax.swing.JComboBox<String> cbVaga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPlaca;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblRPlaca;
    private javax.swing.JLabel lblRetirar;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblVaga;
    private javax.swing.JTable tableStatus;
    private javax.swing.JTextField tfCPlaca;
    private javax.swing.JTextField tfRPlaca;
    private javax.swing.JTextField tfTipo;
    // End of variables declaration//GEN-END:variables
}
